config:
  logs:
    positions_directory: /tmp/positions
    targets:
      - name: kubernetes
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: replace
            source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node
        pipeline_stages:
          - cri: {}
        labels:
          job: kubernetes-pods
    clients:
      - url: http://loki.loki:3100/loki/api/v1/push
