apiVersion: v1
kind: Service
metadata:
  name: telemetry-l4
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: tcp-logs
    port: 1514
    targetPort: 1514
    protocol: TCP
  selector:
    app: telemetry-ingestor
